services:

  couchbase-server-ios-userprofile:
    build: ./src/couchbase-server
    ports:
     - 8091-8097:8091-8097
     - 9123:9123
     - 11207:11207
     - 11210:11210
     - 11280:11280
     - 18091-18097:18091-18097
    environment:  
      - CLUSTER_NAME=couchbase-demo
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=P@ssw0rd12
      - COUCHBASE_BUCKET=userprofile
      - COUCHBASE_BUCKET_RAMSIZE=512
      - COUCHBASE_RBAC_USERNAME=admin
      - COUCHBASE_RBAC_PASSWORD=P@ssw0rd
      - COUCHBASE_RBAC_NAME=admin
      - COUCHBASE_RAM_SIZE=2048
      - COUCHBASE_INDEX_RAM_SIZE=512
    hostname: couchbase-server
    container_name: couchbase-server-ios-userprofile
    working_dir: /opt/couchbase
    stdin_open: true
    tty: true      
    networks:
      - workshop
    entrypoint: [""]
    command: sh -c "/opt/couchbase/init/init-cbserver.sh"

  sync-gateway-ios-userprofile:
    build: ./src/sync-gateway
    ports:
      - 4984-4986:4984-4986
    hostname: sync-gateway
    container_name: sync-gateway-ios-userprofile
    depends_on:
      - couchbase-server-ios-userprofile 
    working_dir: /docker-syncgateway
    stdin_open: true
    tty: true      
    networks:
      - workshop
    entrypoint: [""]
    command: sh -c "/opt/couchbase-sync-gateway/init/init-syncgateway.sh"

networks:
  workshop:
    driver: bridge
